# FROM node:20-alpine

# WORKDIR /app

# COPY package*.json ./
# RUN npm install --production

# COPY . .

# EXPOSE 5000

# CMD ["node", "src/index.js"]
# ```

# ---

# **`server/.dockerignore`**
# ```
# node_modules
# .env
# *.log